spring:
  jpa:
    hiberante:
      ddl-auto: update
      show-sql: true
    database: mysql
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/audiroDB
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 127.0.0.1
    port: 6379
