spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-secret: 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
            client-id: 111272373115-5vbj6rckde2ntanmcchogcsan9aislv8.apps.googleusercontent.com
            scope:
              - email
              - profile

          naver:
            client-secret:
            client-id:
            scope:
              - name
              - email
              - profile_image
            client-name: Naver
            authorization-grant-type: authorization-code
            redirect-uri: http://localhost:8080/login/oauth2/code/naver

        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
