spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-secret: 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
            client-id: 111272373115-5vbj6rckde2ntanmcchogcsan9aislv8.apps.googleusercontent.com
            scope:
              - email
              - profile
            redirect-uri: http://i8a402.p.ssafy.io:80/login/oauth2/code/google
          naver:
            client-secret: JJBfQDo08A
            client-id: xj6iYQrdmJ4LT_8N0kGu
            scope:
              - name
              - email
              - profile_image
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: http://i8a402.p.ssafy.io:8080/login/oauth2/code/naver
          kakao:
            client-secret: 7S4aXXvgDfDeabHg7sDXE3x8bmEVFs7n
            client-id: 36efccc7ac6a65a752e2994d8568eafb
            scope:
              - profile_nickname
              - profile_image
              - account_email
            client-name: Kakao
            authorization-grant-type: authorization_code
            client-authentication-method: POST
            redirect-uri: http://i8a402.p.ssafy.io:8080/login/oauth2/code/kakao
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id