spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/audiroDB
    password: '1234'
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
